Update Wasmtime to v0.30
krustlet/krustlet pull request #681
Opened 2021-09-20 18:05 UTC by radu-matei

This PR updates Wasmtime to v0.30 -- see https://rustsec.org/advisories/RUSTSEC-2021-0110.html

2021-09-20 18:05 UTC, radu-matei commented on crates/wasi-provider/Cargo.toml
> +wasi-experimental-http-wasmtime = { git = "https://github.com/radu-matei/wasi-experimental-http", branch = "wasmtime-v030" }
TODO: update once a new release is available.

2021-09-20 18:19 UTC, radu-matei commented
Note: the failed check is because of an advisory not introduced by this PR -- see https://rustsec.org/advisories/RUSTSEC-2021-0093

2021-09-20 18:52 UTC, thomastaylor312 requested changes
This looks good to go once the experimental http library is updated. However, one of the dependencies in here (possibly in the lock file?) is pulling in a version of crossbeam with a security advisory. The latest patch release (0.8.1) should solve that. If it turns out to be an upstream problem, let's address the issue there

2021-09-20 18:53 UTC, thomastaylor312 commented
@radu-matei This advisory is not appearing in previous runs, so something happened here to bring in a new library. So we should address it here (or at least diagnose and open an upstream issue)

2021-09-20 19:03 UTC, radu-matei commented
Directly updated `crossbeam-deque` to v0.8.1 - see cf7658f210f074092e0ef140a2ae095ea461ca96.

2021-09-21 16:38 UTC, thomastaylor312 approved these changes

2021-09-23 17:12 UTC, radu-matei commented
@thomastaylor312 -- what do you think we should do about the license check for `webpki-roots`?

```
error[L001]: failed to satisfy license requirements
  ┌─ webpki-roots 0.21.1 (registry+rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft
  │
  = webpki-roots v0.21.1
    └── reqwest v0.11.4
        ├── (dev) krustlet v1.0.0-alpha.1
        ├── (dev) kubelet v1.0.0-alpha.1
        │   ├── krustlet v1.0.0-alpha.1 (*)
        │   └── wasi-provider v1.0.0-alpha.1
        │       └── krustlet v1.0.0-alpha.1 (*)
        ├── kubelet v1.0.0-alpha.1 (*)
        ├── oci-distribution v0.7.0
        │   ├── krustlet v1.0.0-alpha.1 (*)
        │   ├── kubelet v1.0.0-alpha.1 (*)
        │   └── (dev) wasi-provider v1.0.0-alpha.1 (*)
        └── wasi-experimental-http-wasmtime v0.6.0
            └── wasi-provider v1.0.0-alpha.1 (*)
```

2021-09-23 23:18 UTC, thomastaylor312 commented
That is a known issue @radu-matei. We have an open issue with the CNCF to grant a license exception to it. For now we are leaving it failing. You should be good to merge whenever

2021-09-30 16:49 UTC, merged